# Splunk Universal Forwarder - inputs.conf
# Windows Event Log + PowerShell + Sysmon
#--------------------------------------------------
# Windows Event Logs (Recommended)
#--------------------------------------------------
[WinEventLog://Security]
disabled = false
index = #place index name created in splunk
sourcetype = WinEventLog:Security

[WinEventLog://System]
disabled = false
index = 
sourcetype = WinEventLog:System

[WinEventLog://Application]
disabled = false
index = 
sourcetype = WinEventLog:Application
#--------------------------------------------------
# PowerShell Operational Logs
#--------------------------------------------------
[WinEventLog://Microsoft-Windows-PowerShell/Operational]
disabled = false
index = 
sourcetype = XmlWinEventLog:Microsoft-Windows-PowerShell/Operational
blacklist = 4100,4105,4106,40962,53504
#--------------------------------------------------
# Sysmon Operational Logs
#--------------------------------------------------
[WinEventLog://Microsoft-Windows-Sysmon/Operational]
index =
disabled = false
renderXml= true
sourcetype = XmlWinEventLog:Microsoft-Windows-Sysmon/Operational

#--------------------------------------------------
# Windows Defender Operational Logs
#--------------------------------------------------
[WinEventLog://Microsoft-Windows-Windows Defender/Operational]
disabled = false
index = 
checkpointInterval = 5
sourcetype = XmlWinEventLog:Microsoft-Windows-Windows Defender/Operational
renderXml = true
blacklist = 1151,1150,2000,1002,1001,1000
#--------------------------------------------------
# Optional: Monitor a Custom Folder
#--------------------------------------------------
[monitor://C:\Logs\MyApp\]
disabled = false
index = 
sourcetype = windows:myapp
recursive = true
#--------------------------------------------------
